language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - WAGTAIL_VERSION=1.5.3

# command to install dependencies
install: 
  - pip install wagtail==$WAGTAIL_VERSION
  - pip install beautifulsoup4==4.4.1

# command to run tests
script: 
  - python manage.py test
sudo: false
